# Generated by Django 3.2.4 on 2021-07-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JobTitle', models.CharField(max_length=100)),
                ('CompanyName', models.CharField(max_length=100)),
                ('DateCompleted', models.DateField()),
                ('Status', models.CharField(choices=[('S', 'Sent'), ('I1', 'Interview[1]'), ('I2', 'Interview[2]'), ('I3', 'Interview[3]')], max_length=15)),
                ('InterviewDate', models.DateField()),
                ('Review', models.CharField(choices=[('A', 'Accepted'), ('R', 'Rejected')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='CommonInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ResumeFileName', models.CharField(max_length=100)),
                ('FullName', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Phone', models.IntegerField()),
                ('CurrentCompany', models.CharField(max_length=100)),
                ('LinkedIn', models.CharField(max_length=100)),
                ('Twitter', models.CharField(max_length=100)),
                ('Github', models.CharField(max_length=100)),
                ('Portfolio', models.CharField(max_length=100)),
                ('OtherWebsite', models.CharField(max_length=100)),
            ],
        ),
    ]
