# Generated by Django 3.2.4 on 2021-07-05 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JoblicantApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='Review',
        ),
        migrations.AddField(
            model_name='application',
            name='Result',
            field=models.CharField(blank=True, choices=[('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='DateCompleted',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='InterviewDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='Status',
            field=models.CharField(choices=[('SENT', 'Sent'), ('INTERVIEWONE', 'Interview[1]'), ('INTERVIEWTWO', 'Interview[2]'), ('INTERVIEWTHREE', 'Interview[3]')], max_length=15),
        ),
    ]
