# Generated by Django 3.2.4 on 2021-07-05 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JoblicantApp', '0002_auto_20210705_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commoninformation',
            name='CurrentCompany',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='commoninformation',
            name='Email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='commoninformation',
            name='FullName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='commoninformation',
            name='Github',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='commoninformation',
            name='LinkedIn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='commoninformation',
            name='OtherWebsite',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='commoninformation',
            name='Phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commoninformation',
            name='Portfolio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='commoninformation',
            name='ResumeFileName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='commoninformation',
            name='Twitter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
