# Generated by Django 3.2.4 on 2021-07-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JoblicantApp', '0003_auto_20210705_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='Result',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='Status',
            field=models.CharField(max_length=100),
        ),
    ]
